### ISSUE TITLE
Support for `*.cfg`, `*.json`, `*.json5`, `*.properties`, `*.txt`

### ISSUE THREAD

**Issue by thimblebird** [Darkere/ConfigSwapper#2]
i've seen you mentioned this in the mod description; still, here's an issue to track the progress.

is the file type limited to `toml` for a reason, or are other file types "just" not yet implemented?

**Comment by Darkere** [comment]
I need to update the description. I've already put in a fallback where it just overrides the file. So they work.

**Comment by thimblebird** [comment]
all of these file types? even `*.json5`? because i've tried with the REI config and... nothing happened when switching modes, tested with the `overlayEnabled` option in the config

**Comment by Darkere** [comment]
check or post logs. It would work with any file, unless it was blocked somehow.

**Comment by thimblebird** [comment]
yeah... you're right. restart was required, but i never noticed because i kept switching in-game which meant whenever i would eventually restart, it was back to the mode i had when first starting the game. thanks for your time <3
