### ISSUE TITLE
[Docs] Serverconfigs

### ISSUE THREAD

**Issue by thimblebird** [Darkere/ConfigSwapper#4]
it's mentioned on the CurseForge description page, but how exactly do serverconfigs work? are there modes for serverconfigs?

**Comment by Darkere** [comment]
Folder structure is like this
configswapper/< your mode >/config or serverconfig/<configs>

**Comment by thimblebird** [comment]
and what do they do? are they server modes? how do i change server modes? `/mode mode-name` in the server console?

**Comment by Darkere** [comment]
Mode is decided by the server. Any users joining will go into the mode the server is on. 

And for each mode both normal and serverconfigs will be replaced.
